type: timed-random
name: "Daily quests"

# You can define the difficulties you want to pick from and how many of each to pick
difficulties:
  easy: 1
  medium: 1
  hard: 1

# At what time to roll new quests (cron syntax) help: https://crontab.guru/
reset-frequency: 0 0 * * *

# How should this pool be displayed in the main menu and where?
menu-item:
  page: 1
  item:
    material: book
    slot: 10
    name: "&aDaily Quests"
    lore:
      - "&7Click to view the daily quests."

menu:
  title: "Daily quests"
  # Where should be put the quests in the menu?
  display-area: [ 19, 20, 21, 22, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34, 37, 38, 39, 40, 41, 42, 43 ]
  # Should the menu have a back/close buttons?
  has-back-button: true
  has-close-button: true
  filler:
    enabled: true
    item:
      material: black_stained_glass_pane
      name: " "
  # You can define custom items here
  custom-items:
    info:
      material: painting
      display_name: "&fDaily quests"
      slot: 4
      lore:
        - "&8Come back every day for new quests."
        - ""
        - "&7Total completed: &f{total_completed}"
      on-click:
        - "[close]"
  # You could override the default items here
#  items: {}


# Should we create a leveling system based on the amount of quests completed in this pool?
leveling:
  enabled: true
  menu:
    title: "Daily Quests levels"
    display-area: [ 19, 20, 21, 22, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34, 37, 38, 39, 40, 41, 42, 43 ]
    # You can override the default items here
    items: {}
    # You can define custom items here for the leveling menu
    custom-items: {}
    filler:
      enabled: true
      item:
        material: black_stained_glass_pane
        name: " "
  requirements:
    - 5
    - 10
    - 30
    - 50
    - 100
  level-matchers:
    default:
      interval: 1
      priority: 0
      rewards: {}
  custom-levels:
    level1:
      level: 1
      rewards:
        my-command-reward:
          type: command
          command: "[console] say %player_name% has reached level 1!"
          display: "&8+&aConsole message"
